---
apiVersion: v1
kind: Namespace
metadata:
  name: v1alpha2-manual
  labels:
    name: v1alpha2-manual
---
apiVersion: cwtest.littlewat.github.io/v1alpha2
kind: TestResource
metadata:
  name: testresource-v1alpha2-manual
  namespace: v1alpha2-manual
spec:
  foo: "v1alpha2Foo"
  bar: "v1alpha2Foo1Bar"
