apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      securityContext: null
#      containers:
#        # each patch needs a 'key' when operating on a YAML list - and we can't use the image because
#        # it may change, but the name shouldn't
#        - name: manager
#          image: docker.artifactory-ha.tri-ad.tech:443/wcm-cityos/infra/kafka-operator:placeholder
