# permissions for end users to view testresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testresource-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: myoperator
    app.kubernetes.io/part-of: myoperator
    app.kubernetes.io/managed-by: kustomize
  name: testresource-viewer-role
rules:
- apiGroups:
  - cwtest.littlewat.github.io
  resources:
  - testresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cwtest.littlewat.github.io
  resources:
  - testresources/status
  verbs:
  - get
